# Generated by Django 5.1.2 on 2025-10-08 15:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('is_default', models.BooleanField(default=False, verbose_name='Categoria Padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(blank=True, help_text='Deixe em branco para categorias padrão do sistema', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['type', 'name'],
                'unique_together': {('name', 'type', 'user')},
            },
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('total_installments', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total de Parcelas')),
                ('default_amount', models.DecimalField(decimal_places=2, help_text='Valor base de cada parcela (pode ser alterado individualmente)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Padrão das Parcelas')),
                ('start_date', models.DateField(help_text='Vencimento da primeira parcela', verbose_name='Data da Primeira Parcela')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_plans', to='finances.category', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Plano de Parcelamento',
                'verbose_name_plural': 'Planos de Parcelamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('day_of_month', models.PositiveIntegerField(help_text='Dia do mês para criar a transação (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia do Mês')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('start_date', models.DateField(help_text='Quando começou este template', verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, help_text='Deixe em branco para recorrência sem fim', null=True, verbose_name='Data de Término')),
                ('last_generated_date', models.DateField(blank=True, help_text='Última vez que uma transação foi gerada', null=True, verbose_name='Última Geração')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_templates', to='finances.category', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_templates', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Template Recorrente',
                'verbose_name_plural': 'Templates Recorrentes',
                'ordering': ['-is_active', 'day_of_month', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('transaction_date', models.DateField(verbose_name='Data da Transação')),
                ('due_date', models.DateField(blank=True, help_text='Data máxima para pagamento (útil para condomínio, contas, etc)', null=True, verbose_name='Data de Vencimento')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='É Recorrente')),
                ('recurrence', models.CharField(choices=[('none', 'Não recorrente'), ('monthly', 'Mensal')], default='none', max_length=10, verbose_name='Recorrência')),
                ('recurrence_end_date', models.DateField(blank=True, help_text='Deixe em branco para recorrência sem fim', null=True, verbose_name='Data Final da Recorrência')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('overdue', 'Atrasado')], default='pending', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finances.category', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número da Parcela')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('generated', 'Transação Gerada'), ('paid', 'Pago'), ('overdue', 'Atrasado')], default='pending', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finances.installmentplan', verbose_name='Plano')),
                ('transaction', models.OneToOneField(blank=True, help_text='Transação criada automaticamente para esta parcela', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment', to='finances.transaction', verbose_name='Transação Gerada')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['plan', 'installment_number'],
            },
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['user', 'is_active'], name='finances_in_user_id_a67b45_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtemplate',
            index=models.Index(fields=['user', 'is_active'], name='finances_re_user_id_73ece5_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtemplate',
            index=models.Index(fields=['day_of_month'], name='finances_re_day_of__a2fe24_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_date'], name='finances_tr_user_id_4337b9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'type'], name='finances_tr_user_id_5d91a0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='finances_tr_status_d5ea9d_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['plan', 'status'], name='finances_in_plan_id_245746_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['due_date', 'status'], name='finances_in_due_dat_c37821_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('plan', 'installment_number')},
        ),
    ]
