# Generated by Django 5.1.2 on 2025-10-09 17:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Nubank Platinum, Itaú Gold', max_length=100, verbose_name='Nome do Cartão')),
                ('brand', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('elo', 'Elo'), ('amex', 'American Express'), ('hipercard', 'Hipercard'), ('other', 'Outro')], max_length=20, verbose_name='Bandeira')),
                ('closing_day', models.PositiveIntegerField(help_text='Dia do mês em que a fatura fecha (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de Fechamento')),
                ('due_day', models.PositiveIntegerField(help_text='Dia do mês em que a fatura vence (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de Vencimento')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Limite total do cartão (opcional)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Limite do Cartão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='credit_card',
            field=models.ForeignKey(blank=True, help_text='Vincula este parcelamento a um cartão de crédito', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_plans', to='finances.creditcard', verbose_name='Cartão de Crédito'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit_card',
            field=models.ForeignKey(blank=True, help_text='Vincula esta transação a um cartão de crédito', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finances.creditcard', verbose_name='Cartão de Crédito'),
        ),
        migrations.CreateModel(
            name='CreditCardInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_month', models.DateField(help_text='Primeiro dia do mês de referência da fatura', verbose_name='Mês de Referência')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Valor total que consta na fatura do banco', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Total da Fatura')),
                ('closing_date', models.DateField(help_text='Data em que a fatura fechou', verbose_name='Data de Fechamento')),
                ('due_date', models.DateField(help_text='Data de vencimento da fatura', verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('overdue', 'Atrasado'), ('partial', 'Parcialmente Pago')], default='pending', max_length=10, verbose_name='Status')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor já pago desta fatura', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Pago')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='finances.creditcard', verbose_name='Cartão de Crédito')),
            ],
            options={
                'verbose_name': 'Fatura de Cartão',
                'verbose_name_plural': 'Faturas de Cartão',
                'ordering': ['-reference_month'],
            },
        ),
        migrations.AddField(
            model_name='installment',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Vincula esta parcela a uma fatura específica do cartão', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installments', to='finances.creditcardinvoice', verbose_name='Fatura'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Vincula esta transação a uma fatura específica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finances.creditcardinvoice', verbose_name='Fatura'),
        ),
        migrations.AddIndex(
            model_name='creditcard',
            index=models.Index(fields=['user', 'is_active'], name='finances_cr_user_id_1caef6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='creditcard',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='creditcardinvoice',
            index=models.Index(fields=['credit_card', 'reference_month'], name='finances_cr_credit__a8ceed_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcardinvoice',
            index=models.Index(fields=['status', 'due_date'], name='finances_cr_status_7c0711_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='creditcardinvoice',
            unique_together={('credit_card', 'reference_month')},
        ),
    ]
