# Generated by Django 5.1.2 on 2025-10-09 20:37

from django.db import migrations


def create_default_categories(apps, schema_editor):
    """
    Cria categorias padrão do sistema para finanças pessoais.
    Estas categorias ficam disponíveis para todos os usuários.
    """
    Category = apps.get_model('finances', 'Category')
    
    # Categorias de Despesa
    expense_categories = [
        {
            'name': 'Alimentação',
            'type': 'expense',
            'description': 'Supermercado, restaurantes, delivery, lanches',
            'is_default': True,
        },
        {
            'name': 'Transporte',
            'type': 'expense',
            'description': 'Combustível, transporte público, Uber, manutenção de veículo',
            'is_default': True,
        },
        {
            'name': 'Moradia',
            'type': 'expense',
            'description': 'Aluguel, condomínio, IPTU, manutenção da casa',
            'is_default': True,
        },
        {
            'name': 'Contas e Serviços',
            'type': 'expense',
            'description': 'Água, luz, internet, telefone, TV por assinatura',
            'is_default': True,
        },
        {
            'name': 'Saúde',
            'type': 'expense',
            'description': 'Plano de saúde, médicos, dentistas, medicamentos, exames',
            'is_default': True,
        },
        {
            'name': 'Educação',
            'type': 'expense',
            'description': 'Mensalidade escolar, cursos, livros, material escolar',
            'is_default': True,
        },
        {
            'name': 'Lazer e Entretenimento',
            'type': 'expense',
            'description': 'Cinema, streaming, viagens, hobbies, eventos',
            'is_default': True,
        },
        {
            'name': 'Vestuário',
            'type': 'expense',
            'description': 'Roupas, calçados, acessórios',
            'is_default': True,
        },
        {
            'name': 'Beleza e Cuidados Pessoais',
            'type': 'expense',
            'description': 'Salão de beleza, barbearia, produtos de higiene e cosméticos',
            'is_default': True,
        },
        {
            'name': 'Pets',
            'type': 'expense',
            'description': 'Veterinário, ração, produtos para animais',
            'is_default': True,
        },
        {
            'name': 'Investimentos',
            'type': 'expense',
            'description': 'Aplicações financeiras, previdência privada, ações',
            'is_default': True,
        },
        {
            'name': 'Seguros',
            'type': 'expense',
            'description': 'Seguro de vida, residencial, automóvel',
            'is_default': True,
        },
        {
            'name': 'Impostos',
            'type': 'expense',
            'description': 'IR, IPVA, taxas governamentais',
            'is_default': True,
        },
        {
            'name': 'Outros - Despesas',
            'type': 'expense',
            'description': 'Outras despesas não categorizadas',
            'is_default': True,
        },
    ]
    
    # Categorias de Receita
    income_categories = [
        {
            'name': 'Salário',
            'type': 'income',
            'description': 'Salário mensal, 13º salário',
            'is_default': True,
        },
        {
            'name': 'Freelance',
            'type': 'income',
            'description': 'Trabalhos autônomos, projetos freelance',
            'is_default': True,
        },
        {
            'name': 'Investimentos',
            'type': 'income',
            'description': 'Rendimentos de aplicações, dividendos, juros',
            'is_default': True,
        },
        {
            'name': 'Aluguel Recebido',
            'type': 'income',
            'description': 'Recebimento de aluguel de imóveis',
            'is_default': True,
        },
        {
            'name': 'Vendas',
            'type': 'income',
            'description': 'Venda de produtos ou bens',
            'is_default': True,
        },
        {
            'name': 'Bonificação',
            'type': 'income',
            'description': 'Bônus, prêmios, comissões',
            'is_default': True,
        },
        {
            'name': 'Outros - Receitas',
            'type': 'income',
            'description': 'Outras receitas não categorizadas',
            'is_default': True,
        },
    ]
    
    # Criar categorias de despesa
    for category_data in expense_categories:
        Category.objects.get_or_create(
            name=category_data['name'],
            type=category_data['type'],
            user=None,  # Categoria do sistema (sem usuário)
            defaults={
                'description': category_data['description'],
                'is_default': category_data['is_default'],
            }
        )
    
    # Criar categorias de receita
    for category_data in income_categories:
        Category.objects.get_or_create(
            name=category_data['name'],
            type=category_data['type'],
            user=None,  # Categoria do sistema (sem usuário)
            defaults={
                'description': category_data['description'],
                'is_default': category_data['is_default'],
            }
        )


def remove_default_categories(apps, schema_editor):
    """
    Remove as categorias padrão do sistema (reverse migration).
    """
    Category = apps.get_model('finances', 'Category')
    
    # Remove todas as categorias padrão do sistema
    Category.objects.filter(is_default=True, user=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_creditcard_installmentplan_credit_card_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, remove_default_categories),
    ]
