# Generated by Django 5.1.2 on 2026-05-11 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_add_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtemplate',
            name='credit_card',
            field=models.ForeignKey(blank=True, help_text='Vincula este template a um cartão de crédito', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_templates', to='finances.creditcard', verbose_name='Cartão de Crédito'),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('credito', 'Crédito'), ('debito', 'Débito'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência'), ('dda', 'DDA')], max_length=20, null=True, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('credito', 'Crédito'), ('debito', 'Débito'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência'), ('dda', 'DDA')], max_length=20, null=True, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='transaction',
            field=models.OneToOneField(blank=True, help_text='Transação criada automaticamente para esta parcela', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installment', to='finances.transaction', verbose_name='Transação Gerada'),
        ),
    ]
